# Generated by Django 3.2.6 on 2022-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_remove_biltorvet_data_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='biltorvet_data',
            name='phone',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
    ]
