# Generated by Django 3.2.6 on 2022-11-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_biltorvet_data_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bilbasen_data',
        ),
        migrations.DeleteModel(
            name='Biltorvet_data',
        ),
    ]
