# Generated by Django 3.2.6 on 2022-11-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_bilbasen_data_biltorvet_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bilbasen_data',
        ),
        migrations.DeleteModel(
            name='Biltorvet_data',
        ),
    ]
