# Generated by Django 3.2.6 on 2022-11-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_biltorvet_data_adcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biltorvet_data',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='biltorvet_data',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
